type User @table {
  firebaseUID: String!
  email: String!
  displayName: String!
  createdAt: Timestamp!
  photoUrl: String
  inviteCode: String
}

type TasteProfile @table {
  user: User!
  categories: [String!]!
  preferences: String!
  updatedAt: Timestamp!
}

type Event @table {
  title: String!
  description: String!
  dateTime: Timestamp!
  location: String!
  host: User!
  createdAt: Timestamp!
  imageUrl: String
  capacity: Int
  eventType: String
}

type Invitation @table(key: ["event", "invitee"]) {
  event: Event!
  invitee: User!
  status: String!
  sentAt: Timestamp!
}

type Aftertaste @table(key: ["event", "attendee"]) {
  event: Event!
  attendee: User!
  rating: Int!
  createdAt: Timestamp!
  comments: String
  attended: Boolean
}